export declare const MONTHS: string[];
export declare const WEEKDAYS_LONG: string[];
export declare const WEEKDAYS_SHORT: string[];
export declare const MONTHS_EN: string[];
export declare const WEEKDAYS_LONG_EN: string[];
export declare const WEEKDAYS_SHORT_EN: string[];
export declare const getDefaultMaxDate: () => Date;
export declare const getDefaultMinDate: () => Date;
export declare const areSameMonth: (date1?: Date | null | undefined, date2?: Date | null | undefined) => boolean;
export declare const areSameDay: (date1: Date, date2: Date) => boolean;
export declare const isLegalDateString: (date: string) => boolean;
export declare const isLegalDateRangeString: (date: string) => boolean | 0;
export declare const convertDateToString: (date?: "" | Date | null | undefined) => string;
export declare const convertDateRangeToString: (range?: [Date | null | undefined, Date | null | undefined] | undefined) => string;
export declare const clone: (d: Date | null | undefined) => Date | null;
export declare const isDayInRange: (date: Date, dateRange: [Date | null | undefined, Date | null | undefined], exclusive?: boolean) => boolean | null;
