import { FocusManager } from "./_util/focusManager"
import "./style/base.css"

export { default as Affix } from "./affix"
export { default as Alert } from "./alert"
export { default as Breadcrumb } from "./breadcrumb"
export { default as Button } from "./button"
export { default as Card } from "./card"
export { default as Cascader } from "./cascader"
export { default as Checkbox } from "./checkbox"
export { default as ColorPicker } from "./color-picker"
export { default as ConfigProvider } from "./config-provider"
export { default as DatePicker } from "./date-picker"
export { default as Dialog } from "./dialog"
export { default as Drawer } from "./drawer"
export { default as Form } from "./form"
export { default as Grid } from "./grid"
export { default as Icon } from "./icon"
export { default as Input } from "./input"
export { default as Layout } from "./layout"
export { default as Menu } from "./menu"
export { default as Message } from "./message"
export { default as Motion } from "./motion"
export { default as Nav } from "./nav"
export { default as NumericInput } from "./numeric-input"
export { default as Pagination } from "./pagination"
export { default as Popover } from "./popover"
export { default as Popconfirm } from "./popconfirm"
export { default as PopTrigger } from "./pop-trigger"
export { default as Portal } from "./portal"
export { default as Radio } from "./radio"
export { default as ResizeObserver } from "./resize-observer"
export { default as Select } from "./select"
export { default as Slider } from "./slider"
export { default as Spinner } from "./spinner"
export { default as Suggest } from "./suggest"
export { default as Switch } from "./switch"
export { default as Tabs } from "./tabs"
export { default as Table } from "./table"
export { default as Tag } from "./tag"
export { default as TimePicker } from "./time-picker"
export { default as Tooltip } from "./tooltip"
export { default as Transition } from "./transition"
export { default as TreeSelect } from "./tree-select"
export { default as Upload } from "./upload"

export { default as ChannelsButton } from "./channels-button"
export { default as ChannelsCheckbox } from "./channels-checkbox"
export { default as ChannelsDialog } from "./channels-dialog"
export { default as ChannelsForm } from "./channels-form"
export { default as ChannelsInput } from "./channels-input"
export { default as ChannelsMessage } from "./channels-message"
export { default as ChannelsPagination } from "./channels-pagination"
export { default as ChannelsRadio } from "./channels-radio"
export { default as ChannelsTabs } from "./channels-tabs"

const fakeFocusEngine = { start: () => true }
const focusEngine =
  typeof document !== "undefined"
    ? new FocusManager(document.documentElement, "adui-focus-disabled")
    : fakeFocusEngine
focusEngine.start()
